using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateCoreBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                return (INamedTypeSymbol)syntaxContext.TargetSymbol;
            })
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates, static (productionContext, featureSymbol) =>
        {
            var targetNamespace = GetTargetNamespace(featureSymbol.ContainingNamespace);
            if (string.IsNullOrWhiteSpace(targetNamespace))
                return;

            var featureName = featureSymbol.Name;
            var isQuery = featureSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute")
                ?.ConstructorArguments.FirstOrDefault().Value is 1; // FeatureType.Query = 1

            var builder = new StringBuilder();
            AppendCore(builder, targetNamespace, featureName, isQuery);

            productionContext.AddSource(
                $"{targetNamespace}.{featureName}.Core.g.cs",
                SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    private static void AppendCore(StringBuilder builder, string targetNamespace, string featureName, bool isQuery)
    {
        var commandOrQuery = isQuery ? "Queries.IQuery" : "Commands.ICommand";
        var mediatorNs = "global::Cortex.Mediator";

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {targetNamespace};");
        builder.AppendLine();
        builder.AppendLine($"public partial class {featureName}");
        builder.AppendLine("{");
        builder.AppendLine("    protected sealed partial class Core : global::ProjectTemplate.Dependencies.Core");
        builder.AppendLine("    {");
        builder.AppendLine("        private Core(global::System.IServiceProvider serviceProvider)");
        builder.AppendLine("            : base(serviceProvider)");
        builder.AppendLine("        { }");
        builder.AppendLine();
        builder.AppendLine($"        public interface I{featureName}EventPresentationLayer : {mediatorNs}.{commandOrQuery}<global::Ardalis.Result.Result<I{featureName}Response>>");
        builder.AppendLine("        {");
        builder.AppendLine($"            I{featureName}Request Request {{ get; }}");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public interface I{featureName}EventApplicationLayer : {mediatorNs}.{commandOrQuery}<global::Ardalis.Result.Result<IApplicationResponseDTO>>");
        builder.AppendLine("        {");
        builder.AppendLine("            IApplicationRequestDTO Request { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public interface I{featureName}EventInfrastructureLayer : {mediatorNs}.{commandOrQuery}<global::Ardalis.Result.Result<IPersistenceResponseDTO>>");
        builder.AppendLine("        {");
        builder.AppendLine("            IPersistenceRequestDTO Request { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Cross-feature read query dispatched from another feature's Application layer. Implement this to expose a read-only query entry point.</summary>");
        builder.AppendLine($"        public interface I{featureName}QueryRequestDTO {{ }}");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Response returned by the <c>I{featureName}QueryEventApplicationLayer</c> query.</summary>");
        builder.AppendLine($"        public interface I{featureName}QueryResponseDTO {{ }}");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Query event dispatched by another feature's Application layer via <c>IApplicationMediator</c>. Must not mutate state.</summary>");
        builder.AppendLine($"        public interface I{featureName}QueryEventApplicationLayer : global::Cortex.Mediator.Queries.IQuery<global::Ardalis.Result.Result<I{featureName}QueryResponseDTO>>");
        builder.AppendLine("        {");
        builder.AppendLine($"            I{featureName}QueryRequestDTO Request {{ get; }}");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        if (namespaceSymbol is null || namespaceSymbol.IsGlobalNamespace)
        {
            return string.Empty;
        }

        var parts = new List<string>();
        var current = namespaceSymbol;

        while (current != null && !current.IsGlobalNamespace)
        {
            parts.Insert(0, current.Name);
            current = current.ContainingNamespace;
        }

        if (parts.Count > 0 && parts[parts.Count - 1] == "Models")
        {
            parts.RemoveAt(parts.Count - 1);
        }

        return string.Join(".", parts);
    }
}
