using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateServiceProviderConstructorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateModels = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.DomainAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                return (INamedTypeSymbol)syntaxContext.TargetSymbol;
            })
            .Where(static symbol => symbol is not null);

        var compilationAndModels = context.CompilationProvider.Combine(candidateModels.Collect());

        context.RegisterSourceOutput(compilationAndModels, static (productionContext, source) =>
        {
            var (compilation, models) = source;

            foreach (var modelSymbol in models.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                var targetNamespace = GetTargetNamespace(modelSymbol.ContainingNamespace);
                if (string.IsNullOrWhiteSpace(targetNamespace))
                {
                    continue;
                }

                var domainName = modelSymbol.Name.EndsWith("Domain", StringComparison.Ordinal)
                    ? modelSymbol.Name.Substring(0, modelSymbol.Name.Length - "Domain".Length)
                    : modelSymbol.Name;
                var featureName = $"Create{domainName}";
                var layerTypes = GetLayerTypes(compilation, targetNamespace, featureName)
                    .Where(CanGenerateFor)
                    .ToArray();

                if (layerTypes.Length == 0)
                {
                    continue;
                }

                var sourceText = BuildSource(targetNamespace, featureName, layerTypes);
                productionContext.AddSource(GetHintName(targetNamespace, modelSymbol.Name), SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static bool CanGenerateFor(INamedTypeSymbol classSymbol)
    {
        if (!classSymbol.DeclaringSyntaxReferences.Any())
        {
            return false;
        }

        if (classSymbol.BaseType is null || classSymbol.BaseType.SpecialType == SpecialType.System_Object)
        {
            return false;
        }

        if (classSymbol.InstanceConstructors.Any(static ctor =>
                ctor.Parameters.Length == 1 &&
                ctor.Parameters[0].Type is INamedTypeSymbol parameterType &&
                parameterType.ToDisplayString() == "System.IServiceProvider"))
        {
            return false;
        }

        foreach (var syntaxReference in classSymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is ClassDeclarationSyntax declaration && declaration.Modifiers.Any(static modifier => modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            {
                return true;
            }
        }

        return false;
    }

    private static string GetHintName(string targetNamespace, string modelName)
    {
        var ns = string.IsNullOrWhiteSpace(targetNamespace)
            ? "Global"
            : targetNamespace;

        return $"{ns}.{modelName}.ServiceProviderConstructors.g.cs";
    }

    private static string BuildSource(string targetNamespace, string featureName, IReadOnlyList<INamedTypeSymbol> layerTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(targetNamespace))
        {
            builder.Append("namespace ");
            builder.Append(targetNamespace);
            builder.AppendLine(";");
            builder.AppendLine();
        }

        builder.AppendLine("public partial class " + featureName);
        builder.AppendLine("{");

        for (var i = 0; i < layerTypes.Count; i++)
        {
            var layerType = layerTypes[i];

            builder.Append(Indent(1));
            builder.Append(GetTypeModifiers(layerType));
            builder.Append(" partial class ");
            builder.Append(layerType.Name);
            AppendTypeParameters(builder, layerType);
            builder.AppendLine();
            builder.Append(Indent(1));
            builder.AppendLine("{");
            builder.Append(Indent(2));
            builder.Append("private ");
            builder.Append(layerType.Name);
            builder.AppendLine("(global::System.IServiceProvider serviceProvider)");
            builder.Append(Indent(3));
            builder.AppendLine(": base(serviceProvider)");
            builder.Append(Indent(2));
            builder.AppendLine("{");
            builder.Append(Indent(2));
            builder.AppendLine("}");
            builder.Append(Indent(1));
            builder.AppendLine("}");

            if (i < layerTypes.Count - 1)
            {
                builder.AppendLine();
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IEnumerable<INamedTypeSymbol> GetLayerTypes(Compilation compilation, string targetNamespace, string featureName)
    {
        foreach (var suffix in new[] { "PresentationLayer", "ApplicationLayer", "InfrastructureLayer" })
        {
            var handlerType = compilation.GetTypeByMetadataName($"{targetNamespace}.{featureName}+{suffix}");
            if (handlerType is not null)
            {
                yield return handlerType;
            }
        }
    }

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        var namespaceName = namespaceSymbol.IsGlobalNamespace
            ? string.Empty
            : namespaceSymbol.ToDisplayString();

        const string modelsSuffix = ".Models";

        if (namespaceName.EndsWith(modelsSuffix, StringComparison.Ordinal))
        {
            return namespaceName.Substring(0, namespaceName.Length - modelsSuffix.Length);
        }

        return namespaceName;
    }

    private static string GetTypeModifiers(INamedTypeSymbol typeSymbol)
    {
        var modifiers = new List<string>();
        var accessibility = GetAccessibility(typeSymbol.DeclaredAccessibility);
        if (!string.IsNullOrEmpty(accessibility))
        {
            modifiers.Add(accessibility);
        }

        if (typeSymbol.IsSealed)
        {
            modifiers.Add("sealed");
        }
        else if (typeSymbol.IsAbstract)
        {
            modifiers.Add("abstract");
        }

        return string.Join(" ", modifiers);
    }

    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty
    };

    private static void AppendTypeParameters(StringBuilder builder, INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
        {
            return;
        }

        builder.Append('<');
        builder.Append(string.Join(", ", typeSymbol.TypeParameters.Select(static parameter => parameter.Name)));
        builder.Append('>');
    }

    private static string Indent(int level) => new(' ', level * 4);
}
