using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GeneratePresentationBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                return (INamedTypeSymbol)syntaxContext.TargetSymbol;
            })
            .Where(static symbol => symbol is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (productionContext, source) =>
        {
            var (compilation, features) = source;

            foreach (var featureSymbol in features.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                var targetNamespace = GetTargetNamespace(featureSymbol.ContainingNamespace);
                if (string.IsNullOrWhiteSpace(targetNamespace))
                    continue;

                var featureName = featureSymbol.Name;
                var coreType = compilation.GetTypeByMetadataName($"{targetNamespace}.{featureName}+Core");
                if (coreType is null)
                    continue;

                var isQuery = featureSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value is 1; // FeatureType.Query = 1

                var sourceText = BuildSource(targetNamespace, featureName, featureSymbol, coreType, isQuery);
                productionContext.AddSource(GetHintName(targetNamespace, featureName), SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static string BuildSource(string targetNamespace, string featureName, INamedTypeSymbol featureSymbol, INamedTypeSymbol coreType, bool isQuery)
    {
        var coreNs = $"global::{targetNamespace}.{featureName}.Core";
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.Append(targetNamespace);
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public partial class " + featureName);
        builder.AppendLine("{");

        AppendHandler(builder, targetNamespace, featureName, coreNs, isQuery);
        builder.AppendLine();

        AppendForwardHelper(builder, featureName, coreNs, isQuery);
        builder.AppendLine();

        AppendPresentationEvent(builder, targetNamespace, featureName, coreNs);
        builder.AppendLine();

        AppendApplicationEvent(builder, targetNamespace, featureName, coreNs);
        builder.AppendLine();

        var applicationRequestDtoInterface = coreType.GetTypeMembers("IApplicationRequestDTO").FirstOrDefault();
        if (applicationRequestDtoInterface is not null)
        {
            AppendRequestDto(builder, featureName, applicationRequestDtoInterface);
            builder.AppendLine();
        }

        var requestInterface = featureSymbol.GetTypeMembers($"I{featureName}Request").FirstOrDefault();
        if (requestInterface is not null)
        {
            AppendRequest(builder, featureName, requestInterface);
            builder.AppendLine();
        }

        var responseInterface = featureSymbol.GetTypeMembers($"I{featureName}Response").FirstOrDefault();
        if (responseInterface is not null)
        {
            AppendDto(builder, responseInterface);
            builder.AppendLine();
        }

        builder.AppendLine("    public sealed partial class Presentation { }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendHandler(StringBuilder builder, string targetNamespace, string featureName, string coreNs, bool isQuery)
    {
        var handlerName = "PresentationLayer";
        var eventInterfaceName = $"{coreNs}.I{featureName}EventPresentationLayer";
        var resultTypeName = $"global::Ardalis.Result.Result<global::{targetNamespace}.{featureName}.I{featureName}Response>";
        var handlerInterface = isQuery
            ? $"global::Cortex.Mediator.Queries.IQueryHandler<{eventInterfaceName}, {resultTypeName}>"
            : $"global::Cortex.Mediator.Commands.ICommandHandler<{eventInterfaceName}, {resultTypeName}>";

        builder.AppendLine("    public sealed partial class " + handlerName);
        builder.AppendLine("        : global::ProjectTemplate.Dependencies.Presentation, " + handlerInterface);
        builder.AppendLine("    {");
        builder.AppendLine("        public " + handlerName + "(global::System.IServiceProvider serviceProvider)");
        builder.AppendLine("            : base(serviceProvider)");
        builder.AppendLine("        {");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        async global::System.Threading.Tasks.Task<" + resultTypeName + "> " + handlerInterface + ".Handle(" + eventInterfaceName + " @event, global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("        {");
        builder.AppendLine("            LogHandling(new global::ProjectTemplate.Compliance.RedactedLog<global::" + targetNamespace + "." + featureName + ".I" + featureName + "Request>(@event.Request, redactorProvider).ToString());");
        builder.AppendLine();
        builder.AppendLine("            var validator = GetRequiredService<PresentationLayer." + featureName + "RequestValidator>();");
        builder.AppendLine("            if (await validator.ValidateAsync(@event.Request, cancellationToken) is { IsValid: false } validationResult)");
        builder.AppendLine("            {");
        builder.AppendLine("                LogValidationFailed(new global::ProjectTemplate.Compliance.RedactedLog<global::" + targetNamespace + "." + featureName + ".I" + featureName + "Request>(@event.Request, redactorProvider).ToString());");
        builder.AppendLine("                return global::Ardalis.Result.Result.Invalid(validationResult.AsErrors());");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return await PresentationLogic(@event.Request, cancellationToken);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.OperationCanceledException)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                LogUnhandledException(ex);");
        builder.AppendLine("                return global::Ardalis.Result.Result.CriticalError(\"An unexpected error occurred while handling the request.\");");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void LogHandling(string request) => logger.LogInformation(\"Handling " + featureName + " presentation: {Request}\", request);");
        builder.AppendLine("        private void LogValidationFailed(string request) => logger.LogWarning(\"" + featureName + " request validation failed: {Request}\", request);");
        builder.AppendLine("        private void LogError(global::System.Collections.Generic.IEnumerable<string> errors) => logger.LogError(\"" + featureName + " presentation error: {Errors}\", errors);");
        builder.AppendLine("        private void LogUnhandledException(global::System.Exception exception) => logger.LogCritical(exception, \"" + featureName + " unhandled exception in presentation layer\");");
        builder.AppendLine("    }");
    }

    private static void AppendRequestDto(StringBuilder builder, string featureName, INamedTypeSymbol requestDtoInterface)
    {
        builder.AppendLine("    private sealed record " + featureName + "RequestDTO : " + GetTypeName(requestDtoInterface));
        builder.AppendLine("    {");

        foreach (var property in GetProperties(requestDtoInterface))
        {
            builder.Append("        public ");
            builder.Append(GetTypeName(property.Type));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" { get; set; }");

            var initializer = GetInitializer(property.Type);
            if (initializer is not null)
            {
                builder.Append(" = ");
                builder.Append(initializer);
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
    }

    private static void AppendRequest(StringBuilder builder, string featureName, INamedTypeSymbol requestInterface)
    {
        builder.AppendLine("    private sealed record " + featureName + "Request : " + GetTypeName(requestInterface));
        builder.AppendLine("    {");

        foreach (var property in GetProperties(requestInterface))
        {
            builder.Append("        public ");
            builder.Append(GetTypeName(property.Type));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" { get; set; }");

            var initializer = GetInitializer(property.Type);
            if (initializer is not null)
            {
                builder.Append(" = ");
                builder.Append(initializer);
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
    }

    private static void AppendForwardHelper(StringBuilder builder, string featureName, string coreNs, bool isQuery)
    {
        var appEventInterface = $"{coreNs}.I{featureName}EventApplicationLayer";
        var appResultType = $"global::Ardalis.Result.Result<{coreNs}.IApplicationResponseDTO>";
        var forwardMethod = isQuery
            ? $"ForwardToApplicationLayerCoreQuery<{appEventInterface}, {appResultType}>"
            : $"ForwardToApplicationLayerCore<{appEventInterface}, {appResultType}>";

        builder.AppendLine("    partial class PresentationLayer");
        builder.AppendLine("    {");
        builder.AppendLine($"        /// <summary>Forwards the request to the application layer. Use this instead of calling <c>SendCommandAsync</c> directly.</summary>");
        builder.AppendLine($"        private global::System.Threading.Tasks.Task<{appResultType}> ForwardToApplicationLayer(");
        builder.AppendLine($"            {coreNs}.IApplicationRequestDTO request,");
        builder.AppendLine($"            global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine($"            => {forwardMethod}(");
        builder.AppendLine($"                new {featureName}EventApplicationLayer(request), cancellationToken);");
        builder.AppendLine("    }");
    }

    private static void AppendPresentationEvent(StringBuilder builder, string targetNamespace, string featureName, string coreNs)
    {
        var outerNs = $"global::{targetNamespace}.{featureName}";
        builder.AppendLine("    public sealed record " + featureName + "EventPresentationLayer(" + outerNs + ".I" + featureName + "Request request) : " + coreNs + ".I" + featureName + "EventPresentationLayer");
        builder.AppendLine("    {");
        builder.AppendLine("        public " + outerNs + ".I" + featureName + "Request Request { get; } = request ?? throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("    }");
    }

    private static void AppendApplicationEvent(StringBuilder builder, string targetNamespace, string featureName, string coreNs)
    {
        builder.AppendLine("    private sealed class " + featureName + "EventApplicationLayer : " + coreNs + ".I" + featureName + "EventApplicationLayer");
        builder.AppendLine("    {");
        builder.AppendLine("        public " + coreNs + ".IApplicationRequestDTO Request { get; }");
        builder.AppendLine();
        builder.AppendLine("        public " + featureName + "EventApplicationLayer(" + coreNs + ".IApplicationRequestDTO request)");
        builder.AppendLine("        {");
        builder.AppendLine("            Request = request ?? throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendDto(StringBuilder builder, INamedTypeSymbol dtoInterface)
    {
        var dtoName = dtoInterface.Name.StartsWith("I", StringComparison.Ordinal)
            ? dtoInterface.Name.Substring(1)
            : dtoInterface.Name;

        builder.AppendLine("    private sealed class " + dtoName + " : " + GetTypeName(dtoInterface));
        builder.AppendLine("    {");

        foreach (var property in GetProperties(dtoInterface))
        {
            builder.Append("        public ");
            builder.Append(GetTypeName(property.Type));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" { get; set; }");

            var initializer = GetInitializer(property.Type);
            if (initializer is not null)
            {
                builder.Append(" = ");
                builder.Append(initializer);
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
    }

    private static IEnumerable<IPropertySymbol> GetProperties(INamedTypeSymbol interfaceSymbol)
    {
        return interfaceSymbol.AllInterfaces
            .Concat(new[] { interfaceSymbol })
            .SelectMany(static type => type.GetMembers().OfType<IPropertySymbol>())
            .GroupBy(static property => property.Name, StringComparer.Ordinal)
            .Select(static group => group.First());
    }

    private static string? GetInitializer(ITypeSymbol typeSymbol)
    {
        if (typeSymbol.SpecialType == SpecialType.System_String)
        {
            return "string.Empty";
        }

        return typeSymbol.IsReferenceType ? "default!" : null;
    }

    private static string GetTypeName(ITypeSymbol typeSymbol)
        => typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetHintName(string targetNamespace, string featureName)
        => $"{targetNamespace}.{featureName}.PresentationBoilerplate.g.cs";

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        var namespaceName = namespaceSymbol.IsGlobalNamespace
            ? string.Empty
            : namespaceSymbol.ToDisplayString();

        const string modelsSuffix = ".Models";

        if (namespaceName.EndsWith(modelsSuffix, StringComparison.Ordinal))
        {
            return namespaceName.Substring(0, namespaceName.Length - modelsSuffix.Length);
        }

        return namespaceName;
    }
}
