using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateExtensionsBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                var symbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
                var isQuery = symbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value is 1; // FeatureType.Query = 1
                return (Symbol: symbol, IsQuery: isQuery);
            })
            .Where(static t => t.Symbol is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (productionContext, source) =>
        {
            var (compilation, features) = source;

            foreach (var (featureSymbol, isQuery) in features.Distinct())
            {
                var targetNamespace = GetTargetNamespace(featureSymbol.ContainingNamespace);
                if (string.IsNullOrWhiteSpace(targetNamespace))
                    continue;

                var featureName = featureSymbol.Name;

                var requestInterface = featureSymbol.GetTypeMembers($"I{featureName}Request").FirstOrDefault();
                var properties = requestInterface is not null
                    ? GetProperties(requestInterface).ToList()
                    : new List<IPropertySymbol>();

                var sb = new StringBuilder();
                AppendExtensions(sb, targetNamespace, featureName, properties, isQuery);

                productionContext.AddSource(
                    $"{targetNamespace}.{featureName}.Extensions.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }

    private static void AppendExtensions(
        StringBuilder sb,
        string targetNamespace,
        string featureName,
        List<IPropertySymbol> requestProperties,
        bool isQuery)
    {
        var coreNs = $"global::{targetNamespace}.{featureName}.Core";
        var resultType = $"global::Ardalis.Result.Result<global::{targetNamespace}.{featureName}.I{featureName}Response>";
        var dtoType = $"global::{targetNamespace}.{featureName}.{featureName}Request";
        var eventType = $"global::{targetNamespace}.{featureName}.{featureName}EventPresentationLayer";
        var queriesType = "global::ProjectTemplate.Dependencies.Queries";
        var commandsType = "global::ProjectTemplate.Dependencies.Commands";
        var mediatorType = "global::Cortex.Mediator.IMediator";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();

        // ── Builder class ──────────────────────────────────────────────────────────
        sb.AppendLine($"public partial class {featureName}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Fluent builder for dispatching a <c>{featureName}</c> {(isQuery ? "query" : "command")} via the mediator.</summary>");
        sb.AppendLine($"    public sealed class Builder");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {mediatorType} _mediator;");
        sb.AppendLine($"        private readonly {dtoType} _dto = new();");
        sb.AppendLine();
        sb.AppendLine($"        internal Builder({mediatorType} mediator) => _mediator = mediator;");
        sb.AppendLine();

        foreach (var prop in requestProperties)
        {
            var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        /// <summary>Sets the <c>{prop.Name}</c> property on the request.</summary>");
            sb.AppendLine($"        public Builder With{prop.Name}({typeName} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _dto.{prop.Name} = value;");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine($"        /// <summary>Dispatches the {(isQuery ? "query" : "command")} and returns the result.</summary>");
        sb.AppendLine($"        public global::System.Threading.Tasks.Task<{resultType}> Send(");
        sb.AppendLine($"            global::System.Threading.CancellationToken cancellationToken = default)");
        if (isQuery)
        {
            sb.AppendLine($"            => _mediator.SendQueryAsync<{eventType}, {resultType}>(");
        }
        else
        {
            sb.AppendLine($"            => _mediator.SendCommandAsync<{eventType}, {resultType}>(");
        }
        sb.AppendLine($"                new {eventType}(_dto), cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Extension methods ──────────────────────────────────────────────────────
        // Queries  → Queries struct (application layers)
        // Commands → Commands struct (command infrastructure layers)
        // Both     → raw IMediator  (endpoints, workers, tests)
        sb.AppendLine($"public static partial class {featureName}Extensions");
        sb.AppendLine("{");

        var layerType = isQuery ? queriesType : commandsType;
        var layerLabel = isQuery ? "query from an application layer" : "command from a command infrastructure layer";

        // Layer-surface builder overload
        sb.AppendLine($"    /// <summary>Returns a fluent builder for dispatching the <c>{featureName}</c> {layerLabel}.</summary>");
        sb.AppendLine($"    public static {featureName}.Builder {featureName}(");
        sb.AppendLine($"        this {layerType} surface)");
        sb.AppendLine($"        => new {featureName}.Builder(surface.Inner);");
        sb.AppendLine();

        // Layer-surface DTO overload
        sb.AppendLine($"    /// <summary>Dispatches the <c>{featureName}</c> {layerLabel} from an existing request.</summary>");
        sb.AppendLine($"    public static global::System.Threading.Tasks.Task<{resultType}> {featureName}(");
        sb.AppendLine($"        this {layerType} surface,");
        sb.AppendLine($"        global::{targetNamespace}.{featureName}.I{featureName}Request request,");
        sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken = default)");
        if (isQuery)
        {
            sb.AppendLine($"        => surface.Inner.SendQueryAsync<{eventType}, {resultType}>(");
        }
        else
        {
            sb.AppendLine($"        => surface.Inner.SendCommandAsync<{eventType}, {resultType}>(");
        }
        sb.AppendLine($"            new {eventType}(request), cancellationToken);");
        sb.AppendLine();

        // Raw IMediator builder overload
        sb.AppendLine($"    /// <summary>Returns a fluent builder for dispatching the <c>{featureName}</c> feature via the raw mediator (endpoints / workers / tests).</summary>");
        sb.AppendLine($"    public static {featureName}.Builder {featureName}(");
        sb.AppendLine($"        this {mediatorType} mediator)");
        sb.AppendLine($"        => new {featureName}.Builder(mediator);");
        sb.AppendLine();

        // Raw IMediator DTO overload
        sb.AppendLine($"    /// <summary>Dispatches the <c>{featureName}</c> feature via the raw mediator from an existing request.</summary>");
        sb.AppendLine($"    public static global::System.Threading.Tasks.Task<{resultType}> {featureName}(");
        sb.AppendLine($"        this {mediatorType} mediator,");
        sb.AppendLine($"        global::{targetNamespace}.{featureName}.I{featureName}Request request,");
        sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken = default)");
        if (isQuery)
        {
            sb.AppendLine($"        => mediator.SendQueryAsync<{eventType}, {resultType}>(");
        }
        else
        {
            sb.AppendLine($"        => mediator.SendCommandAsync<{eventType}, {resultType}>(");
        }
        sb.AppendLine($"            new {eventType}(request), cancellationToken);");


        sb.AppendLine("}");
    }

    private static IEnumerable<IPropertySymbol> GetProperties(INamedTypeSymbol interfaceSymbol)
    {
        return interfaceSymbol.AllInterfaces
            .Concat(new[] { interfaceSymbol })
            .SelectMany(static type => type.GetMembers().OfType<IPropertySymbol>())
            .GroupBy(static property => property.Name, StringComparer.Ordinal)
            .Select(static group => group.First());
    }

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        if (namespaceSymbol is null || namespaceSymbol.IsGlobalNamespace)
        {
            return string.Empty;
        }

        var parts = new List<string>();
        var current = namespaceSymbol;

        while (current != null && !current.IsGlobalNamespace)
        {
            parts.Insert(0, current.Name);
            current = current.ContainingNamespace;
        }

        if (parts.Count > 0 && parts[parts.Count - 1] == "Models")
        {
            parts.RemoveAt(parts.Count - 1);
        }

        return string.Join(".", parts);
    }
}
