using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateInfrastructureBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                var symbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
                var isQuery = symbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value is 1; // FeatureType.Query = 1
                return (Symbol: symbol, IsQuery: isQuery);
            })
            .Where(static t => t.Symbol is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (productionContext, source) =>
        {
            var (compilation, features) = source;

            foreach (var (featureSymbol, isQuery) in features.Distinct())
            {
                var targetNamespace = GetTargetNamespace(featureSymbol.ContainingNamespace);
                if (string.IsNullOrWhiteSpace(targetNamespace))
                    continue;

                var featureName = featureSymbol.Name;
                var coreType = compilation.GetTypeByMetadataName($"{targetNamespace}.{featureName}+Core");
                if (coreType is null)
                    continue;

                var domainName = GetDomainName(featureSymbol.ContainingNamespace);

                var sourceText = BuildSource(targetNamespace, featureName, coreType, domainName, isQuery);
                productionContext.AddSource(GetHintName(targetNamespace, featureName), SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static string BuildSource(string targetNamespace, string featureName, INamedTypeSymbol coreType, string domainName, bool isQuery)
    {
        var coreNs = $"global::{targetNamespace}.{featureName}.Core";
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.Append(targetNamespace);
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public partial class " + featureName);
        builder.AppendLine("{");

        AppendHandler(builder, targetNamespace, featureName, coreNs, domainName, isQuery);
        builder.AppendLine();

        var persistenceResponseInterface = coreType.GetTypeMembers("IPersistenceResponseDTO").FirstOrDefault();
        if (persistenceResponseInterface is not null)
        {
            AppendDto(builder, persistenceResponseInterface);
            builder.AppendLine();
        }

        builder.AppendLine("    private sealed partial class Infrastructure { }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendHandler(StringBuilder builder, string targetNamespace, string featureName, string coreNs, string domainName, bool isQuery)
    {
        var handlerName = "InfrastructureLayer";
        var eventInterfaceName = $"{coreNs}.I{featureName}EventInfrastructureLayer";
        var resultTypeName = $"global::Ardalis.Result.Result<{coreNs}.IPersistenceResponseDTO>";
        var entityTypeName = domainName + "Entity";
        var handlerInterface = isQuery
            ? $"global::Cortex.Mediator.Queries.IQueryHandler<{eventInterfaceName}, {resultTypeName}>"
            : $"global::Cortex.Mediator.Commands.ICommandHandler<{eventInterfaceName}, {resultTypeName}>";

        builder.AppendLine("    public sealed partial class " + handlerName);
        builder.AppendLine("        : global::ProjectTemplate.Dependencies.Infrastructure, " + handlerInterface);
        builder.AppendLine("    {");
        builder.AppendLine("        private new readonly global::Microsoft.Extensions.Logging.ILogger logger;");
        builder.AppendLine("        private new global::Microsoft.Extensions.Compliance.Redaction.IRedactorProvider redactorProvider => base.redactorProvider;");
        builder.AppendLine();
        builder.AppendLine("        public " + handlerName + "(global::System.IServiceProvider serviceProvider)");
        builder.AppendLine("            : base(serviceProvider)");
        builder.AppendLine("        {");
        builder.AppendLine("            logger = base.logger;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        async global::System.Threading.Tasks.Task<" + resultTypeName + "> " + handlerInterface + ".Handle(" + eventInterfaceName + " command, global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("        {");
        builder.AppendLine("            LogPersisting(new global::ProjectTemplate.Compliance.RedactedLog<" + coreNs + ".IPersistenceRequestDTO>(command.Request, redactorProvider).ToString());");
        builder.AppendLine("            var entity = command.Request.Adapt<" + entityTypeName + ">();");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return await InfrastructureLogic(entity, cancellationToken);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.OperationCanceledException)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                LogUnhandledException(ex);");
        builder.AppendLine("                return global::Ardalis.Result.Result.CriticalError(\"An unexpected error occurred while persisting the entity.\");");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    partial class " + handlerName);
        builder.AppendLine("    {");
        builder.AppendLine("        private void LogPersisting(string request) => logger.LogInformation(\"Persisting " + featureName.Replace("Create", "") + " entity: {Request}\", request);");
        builder.AppendLine("        private void LogPersistenceFailed(string request) => logger.LogError(\"" + featureName + " persistence failed: {Request}\", request);");
        builder.AppendLine("        private void LogUnhandledException(global::System.Exception exception) => logger.LogCritical(exception, \"" + featureName + " unhandled exception in infrastructure layer\");");
        builder.AppendLine("    }");
    }

    private static void AppendDto(StringBuilder builder, INamedTypeSymbol dtoInterface)
    {
        var dtoName = dtoInterface.Name.StartsWith("I", StringComparison.Ordinal)
            ? dtoInterface.Name.Substring(1)
            : dtoInterface.Name;

        builder.AppendLine("    private sealed class " + dtoName + " : " + GetTypeName(dtoInterface));
        builder.AppendLine("    {");

        foreach (var property in GetProperties(dtoInterface))
        {
            builder.Append("        public ");
            builder.Append(GetTypeName(property.Type));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" { get; set; }");

            var initializer = GetInitializer(property.Type);
            if (initializer is not null)
            {
                builder.Append(" = ");
                builder.Append(initializer);
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
    }

    private static IEnumerable<IPropertySymbol> GetProperties(INamedTypeSymbol interfaceSymbol)
    {
        return interfaceSymbol.AllInterfaces
            .Concat(new[] { interfaceSymbol })
            .SelectMany(static type => type.GetMembers().OfType<IPropertySymbol>())
            .GroupBy(static property => property.Name, StringComparer.Ordinal)
            .Select(static group => group.First());
    }

    private static string? GetInitializer(ITypeSymbol typeSymbol)
    {
        if (typeSymbol.SpecialType == SpecialType.System_String)
        {
            return "string.Empty";
        }

        return typeSymbol.IsReferenceType ? "default!" : null;
    }

    private static string GetTypeName(ITypeSymbol typeSymbol)
        => typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetHintName(string targetNamespace, string featureName)
        => $"{targetNamespace}.{featureName}.InfrastructureBoilerplate.g.cs";

    private static string GetDomainName(INamespaceSymbol namespaceSymbol)
    {
        var ns = namespaceSymbol;
        while (ns != null && !ns.IsGlobalNamespace)
        {
            if (!string.IsNullOrWhiteSpace(ns.Name))
                return ns.Name;
            ns = ns.ContainingNamespace;
        }
        return string.Empty;
    }

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        var namespaceName = namespaceSymbol.IsGlobalNamespace
            ? string.Empty
            : namespaceSymbol.ToDisplayString();

        const string modelsSuffix = ".Models";

        if (namespaceName.EndsWith(modelsSuffix, StringComparison.Ordinal))
        {
            return namespaceName.Substring(0, namespaceName.Length - modelsSuffix.Length);
        }

        return namespaceName;
    }
}
