// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateDbContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var domainClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.DomainAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol)
            .Where(static s => s is not null)
            .Collect();

        context.RegisterSourceOutput(domainClasses, static (productionContext, domainSymbols) =>
        {
            var entries = new List<(string FeatureName, string EntityTypeFqn, INamedTypeSymbol PersistenceInterface)>();

            foreach (var domainSymbol in domainSymbols)
            {
                var persistenceInterface = FindNestedInterfaceWithAttribute(
                    domainSymbol, "ProjectTemplate.Dependencies.Attributes.PersistenceModelAttribute");

                if (persistenceInterface is null)
                    continue;

                var ns = domainSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : domainSymbol.ContainingNamespace.ToDisplayString();

                if (string.IsNullOrWhiteSpace(ns))
                    continue;

                var rawName = domainSymbol.Name;
                var domainName = rawName.EndsWith("Domain", StringComparison.Ordinal)
                    ? rawName.Substring(0, rawName.Length - "Domain".Length)
                    : rawName;

                var featureName = $"Create{domainName}";
                var entityName = StripLeadingI(persistenceInterface.Name);
                var entityTypeFqn = $"{ns}.{featureName}.InfrastructureLayer.{entityName}";

                entries.Add((featureName, entityTypeFqn, persistenceInterface));
            }

            if (entries.Count == 0)
                return;

            // ── AppDbContext partial ─────────────────────────────────────────────
            // Delegates all entity registration to each InfrastructureLayer.RegisterEntities
            // so AppDbContext never names the private entity types directly.
            var dbContextSb = new StringBuilder();
            dbContextSb.AppendLine("// <auto-generated/>");
            dbContextSb.AppendLine("#nullable enable");
            dbContextSb.AppendLine();
            dbContextSb.AppendLine("namespace ProjectTemplate.Data;");
            dbContextSb.AppendLine();
            dbContextSb.AppendLine("internal partial class AppDbContext");
            dbContextSb.AppendLine("{");
            dbContextSb.AppendLine("    partial void ApplyGeneratedConfigurations(global::Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)");
            dbContextSb.AppendLine("    {");
            foreach (var (featureName, entityTypeFqn, _) in entries)
            {
                // Derive the fully-qualified InfrastructureLayer type path from the entity FQN.
                // entityTypeFqn = "ProjectTemplate.Domains.Sample.CreateSample.InfrastructureLayer.SampleEntity"
                // We want      = "ProjectTemplate.Domains.Sample.CreateSample.InfrastructureLayer"
                var lastDot = entityTypeFqn.LastIndexOf('.');
                var infraLayerFqn = entityTypeFqn.Substring(0, lastDot);
                dbContextSb.AppendLine($"        global::{infraLayerFqn}.RegisterEntities(modelBuilder);");
            }
            dbContextSb.AppendLine("    }");
            dbContextSb.AppendLine("}");

            productionContext.AddSource(
                "ProjectTemplate.Data.AppDbContext.g.cs",
                SourceText.From(dbContextSb.ToString(), Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? FindNestedInterfaceWithAttribute(INamedTypeSymbol domainSymbol, string attributeFullName)
    {
        foreach (var member in domainSymbol.GetTypeMembers())
        {
            if (member.TypeKind != TypeKind.Interface)
                continue;

            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == attributeFullName)
                    return member;
            }
        }
        return null;
    }

    private static string StripLeadingI(string name)
        => name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1])
            ? name.Substring(1)
            : name;
}
