using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateApplicationBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
            {
                cancellationToken.ThrowIfCancellationRequested();
                return (INamedTypeSymbol)syntaxContext.TargetSymbol;
            })
            .Where(static symbol => symbol is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (productionContext, source) =>
        {
            var (compilation, features) = source;

            foreach (var featureSymbol in features.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                var targetNamespace = GetTargetNamespace(featureSymbol.ContainingNamespace);
                if (string.IsNullOrWhiteSpace(targetNamespace))
                    continue;

                var featureName = featureSymbol.Name;
                var coreType = compilation.GetTypeByMetadataName($"{targetNamespace}.{featureName}+Core");
                if (coreType is null)
                    continue;

                // domainName = last segment of the namespace (e.g. "Sample" from "ProjectTemplate.Domains.Sample")
                var domainName = GetDomainName(featureSymbol.ContainingNamespace);
                var isQuery = featureSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value is 1; // FeatureType.Query = 1

                var sourceText = BuildSource(targetNamespace, featureName, coreType, domainName, isQuery);
                productionContext.AddSource(GetHintName(targetNamespace, featureName), SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static string BuildSource(string targetNamespace, string featureName, INamedTypeSymbol coreType, string domainName, bool isQuery)
    {
        var coreNs = $"global::{targetNamespace}.{featureName}.Core";
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.Append(targetNamespace);
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public partial class " + featureName);
        builder.AppendLine("{");

        AppendHandler(builder, targetNamespace, featureName, coreNs, domainName, isQuery);
        builder.AppendLine();

        AppendForwardHelper(builder, featureName, coreNs, isQuery);
        builder.AppendLine();

        AppendRequestWrapper(builder, targetNamespace, featureName, coreNs);
        builder.AppendLine();

        var applicationResponseInterface = coreType.GetTypeMembers("IApplicationResponseDTO").FirstOrDefault();
        if (applicationResponseInterface is not null)
        {
            AppendDto(builder, applicationResponseInterface);
            builder.AppendLine();
        }

        builder.AppendLine("    public sealed partial class Application { }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendHandler(StringBuilder builder, string targetNamespace, string featureName, string coreNs, string domainName, bool isQuery)
    {
        var handlerName = "ApplicationLayer";
        var eventInterfaceName = $"{coreNs}.I{featureName}EventApplicationLayer";
        var resultTypeName = $"global::Ardalis.Result.Result<{coreNs}.IApplicationResponseDTO>";
        var modelTypeName = domainName;
        var businessValidatorName = domainName + "BusinessValidator";
        var handlerInterface = isQuery
            ? $"global::Cortex.Mediator.Queries.IQueryHandler<{eventInterfaceName}, {resultTypeName}>"
            : $"global::Cortex.Mediator.Commands.ICommandHandler<{eventInterfaceName}, {resultTypeName}>";

        builder.AppendLine("    public sealed partial class " + handlerName);
        builder.AppendLine("        : global::ProjectTemplate.Dependencies.Application, " + handlerInterface);
        builder.AppendLine("    {");
        builder.AppendLine("        public " + handlerName + "(global::System.IServiceProvider serviceProvider)");
        builder.AppendLine("            : base(serviceProvider)");
        builder.AppendLine("        {");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        async global::System.Threading.Tasks.Task<" + resultTypeName + "> " + handlerInterface + ".Handle(" + eventInterfaceName + " command, global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("        {");
        builder.AppendLine("            LogExecuting(new global::ProjectTemplate.Compliance.RedactedLog<" + coreNs + ".IApplicationRequestDTO>(command.Request, redactorProvider).ToString());");
        builder.AppendLine();
        builder.AppendLine("            var sample = command.Request.Adapt<" + modelTypeName + ">();");
        builder.AppendLine("            var validator = GetRequiredService<ApplicationLayer." + businessValidatorName + ">();");
        builder.AppendLine("            if (await validator.ValidateAsync(sample, cancellationToken) is { IsValid: false } validationResult)");
        builder.AppendLine("            {");
        builder.AppendLine("                LogBusinessValidationFailed(new global::ProjectTemplate.Compliance.RedactedLog<" + coreNs + ".IApplicationRequestDTO>(command.Request, redactorProvider).ToString());");
        builder.AppendLine("                return global::Ardalis.Result.Result.Invalid(validationResult.AsErrors());");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                return await ApplicationLogic(sample, cancellationToken);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.OperationCanceledException)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                LogUnhandledException(ex);");
        builder.AppendLine("                return global::Ardalis.Result.Result.CriticalError(\"An unexpected error occurred while executing the application logic.\");");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    partial class " + handlerName);
        builder.AppendLine("    {");
        builder.AppendLine("        private void LogExecuting(string request) => logger.LogInformation(\"Executing " + featureName + " application logic: {Request}\", request);");
        builder.AppendLine("        private void LogBusinessValidationFailed(string request) => logger.LogWarning(\"" + featureName + " business validation failed: {Request}\", request);");
        builder.AppendLine("        private void LogError(string errors) => logger.LogError(\"" + featureName + " application error: {Errors}\", errors);");
        builder.AppendLine("        private void LogUnhandledException(global::System.Exception exception) => logger.LogCritical(exception, \"" + featureName + " unhandled exception in application layer\");");
        builder.AppendLine("    }");
    }

    private static void AppendForwardHelper(StringBuilder builder, string featureName, string coreNs, bool isQuery)
    {
        var infraEventInterface = $"{coreNs}.I{featureName}EventInfrastructureLayer";
        var infraResultType = $"global::Ardalis.Result.Result<{coreNs}.IPersistenceResponseDTO>";
        var forwardMethod = isQuery
            ? $"ForwardQuery<{infraEventInterface}, {infraResultType}>"
            : $"ForwardCommand<{infraEventInterface}, {infraResultType}>";

        builder.AppendLine("    partial class ApplicationLayer");
        builder.AppendLine("    {");
        builder.AppendLine($"        /// <summary>Forwards the request to the infrastructure layer. Use this instead of calling <c>SendCommandAsync</c> directly.</summary>");
        builder.AppendLine($"        private global::System.Threading.Tasks.Task<{infraResultType}> ForwardToInfrastructureLayer(");
        builder.AppendLine($"            {coreNs}.IPersistenceRequestDTO request,");
        builder.AppendLine($"            global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine($"            => {forwardMethod}(");
        builder.AppendLine($"                new {featureName}EventInfrastructureLayer(request), cancellationToken);");
        builder.AppendLine("    }");
    }

    private static void AppendRequestWrapper(StringBuilder builder, string targetNamespace, string featureName, string coreNs)
    {
        builder.AppendLine("    private sealed class " + featureName + "EventInfrastructureLayer : " + coreNs + ".I" + featureName + "EventInfrastructureLayer");
        builder.AppendLine("    {");
        builder.AppendLine("        public " + featureName + "EventInfrastructureLayer(" + coreNs + ".IPersistenceRequestDTO request)");
        builder.AppendLine("        {");
        builder.AppendLine("            Request = request ?? throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public " + coreNs + ".IPersistenceRequestDTO Request { get; }");
        builder.AppendLine("    }");
    }

    private static void AppendDto(StringBuilder builder, INamedTypeSymbol dtoInterface)
    {
        var dtoName = dtoInterface.Name.StartsWith("I", StringComparison.Ordinal)
            ? dtoInterface.Name.Substring(1)
            : dtoInterface.Name;

        builder.AppendLine("    private sealed class " + dtoName + " : " + GetTypeName(dtoInterface));
        builder.AppendLine("    {");

        foreach (var property in GetProperties(dtoInterface))
        {
            builder.Append("        public ");
            builder.Append(GetTypeName(property.Type));
            builder.Append(' ');
            builder.Append(property.Name);
            builder.Append(" { get; set; }");

            var initializer = GetInitializer(property.Type);
            if (initializer is not null)
            {
                builder.Append(" = ");
                builder.Append(initializer);
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
    }

    private static IEnumerable<IPropertySymbol> GetProperties(INamedTypeSymbol interfaceSymbol)
    {
        return interfaceSymbol.AllInterfaces
            .Concat(new[] { interfaceSymbol })
            .SelectMany(static type => type.GetMembers().OfType<IPropertySymbol>())
            .GroupBy(static property => property.Name, StringComparer.Ordinal)
            .Select(static group => group.First());
    }

    private static string? GetInitializer(ITypeSymbol typeSymbol)
    {
        if (typeSymbol.SpecialType == SpecialType.System_String)
        {
            return "string.Empty";
        }

        return typeSymbol.IsReferenceType ? "default!" : null;
    }

    private static string GetTypeName(ITypeSymbol typeSymbol)
        => typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetHintName(string targetNamespace, string featureName)
        => $"{targetNamespace}.{featureName}.ApplicationBoilerplate.g.cs";

    private static string GetDomainName(INamespaceSymbol namespaceSymbol)
    {
        // Returns the last segment of the namespace (e.g. "Sample" from "ProjectTemplate.Domains.Sample")
        var ns = namespaceSymbol;
        while (ns != null && !ns.IsGlobalNamespace)
        {
            if (!string.IsNullOrWhiteSpace(ns.Name))
                return ns.Name;
            ns = ns.ContainingNamespace;
        }
        return string.Empty;
    }

    private static string GetTargetNamespace(INamespaceSymbol namespaceSymbol)
    {
        var namespaceName = namespaceSymbol.IsGlobalNamespace
            ? string.Empty
            : namespaceSymbol.ToDisplayString();

        const string modelsSuffix = ".Models";

        if (namespaceName.EndsWith(modelsSuffix, StringComparison.Ordinal))
        {
            return namespaceName.Substring(0, namespaceName.Length - modelsSuffix.Length);
        }

        return namespaceName;
    }
}
