// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ProjectTemplate.Generators;

[Generator]
public sealed class GenerateDbContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var domainClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.DomainAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol)
            .Where(static s => s is not null)
            .Collect();

        var featureClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ProjectTemplate.Dependencies.Attributes.FeatureAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol)
            .Where(static s => s is not null)
            .Collect();

        var combined = domainClasses.Combine(featureClasses);

        context.RegisterSourceOutput(combined, static (productionContext, source) =>
        {
            var (domainSymbols, features) = source;
            var hasEntries = false;

            // ── AppDbContext partial ─────────────────────────────────────────────
            // Delegates all entity registration to each feature's InfrastructureLayer.RegisterEntities
            // so AppDbContext never names the feature-private entity types directly.
            var dbContextSb = new StringBuilder();
            dbContextSb.AppendLine("// <auto-generated/>");
            dbContextSb.AppendLine("#nullable enable");
            dbContextSb.AppendLine();
            dbContextSb.AppendLine("namespace ProjectTemplate.Data;");
            dbContextSb.AppendLine();
            dbContextSb.AppendLine("internal partial class AppDbContext");
            dbContextSb.AppendLine("{");
            dbContextSb.AppendLine("    partial void ApplyGeneratedConfigurations(global::Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)");
            dbContextSb.AppendLine("    {");

            foreach (var domainSymbol in domainSymbols)
            {
                var persistenceInterface = FindNestedInterfaceWithAttribute(
                    domainSymbol, "ProjectTemplate.Dependencies.Attributes.PersistenceModelAttribute");

                if (persistenceInterface is null)
                    continue;

                var ns = domainSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : domainSymbol.ContainingNamespace.ToDisplayString();

                if (string.IsNullOrWhiteSpace(ns))
                    continue;

                var rawName = domainSymbol.Name;
                var domainName = rawName.EndsWith("Domain", StringComparison.Ordinal)
                    ? rawName.Substring(0, rawName.Length - "Domain".Length)
                    : rawName;

                // Find all [Feature] classes in the same namespace as this domain.
                var matchedFeatureNames = new List<string>();
                foreach (var feature in features.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
                {
                    if (feature.ContainingNamespace.IsGlobalNamespace) continue;
                    if (feature.ContainingNamespace.ToDisplayString() == ns)
                        matchedFeatureNames.Add(feature.Name);
                }

                // Fall back to Create{DomainName} when no [Feature] classes are present.
                var featureNames = matchedFeatureNames.Count > 0
                    ? matchedFeatureNames
                    : new List<string> { $"Create{domainName}" };

                foreach (var featureName in featureNames)
                {
                    dbContextSb.AppendLine($"        global::{ns}.{featureName}.InfrastructureLayer.RegisterEntities(modelBuilder);");
                    hasEntries = true;
                }
            }

            dbContextSb.AppendLine("    }");
            dbContextSb.AppendLine("}");

            if (!hasEntries)
                return;

            productionContext.AddSource(
                "ProjectTemplate.Data.AppDbContext.g.cs",
                SourceText.From(dbContextSb.ToString(), Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? FindNestedInterfaceWithAttribute(INamedTypeSymbol domainSymbol, string attributeFullName)
    {
        foreach (var member in domainSymbol.GetTypeMembers())
        {
            if (member.TypeKind != TypeKind.Interface)
                continue;

            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == attributeFullName)
                    return member;
            }
        }
        return null;
    }
}
